# -*- coding: utf-8 -*-
"""ListaExercicio3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzRYAWvSHskaDdS-NvDIdapC-ENL2hpA

# Exercício 1

Escreva um programa que receba um número natural n na entrada e imprima n! (fatorial) na saída.

Exemplo:

Digite o valor de n: 5

120

Dica: lembre-se que o fatorial de 0 vale 1
"""

n = int(input("Digite o valor de n: "))
fatorial = 1
if n > 0:
    for i in range(1, n + 1):
        fatorial *= i
print(fatorial)

"""# Exercício 2

Receba um número inteiro positivo na entrada e imprima os n primeiros números ímpares naturais. Para a saída, siga o formato do exemplo abaixo.

Exemplo:

Digite o valor de n: 5

1

3

5

7

9
"""

n = int(input("Digite o valor de n: "))
numero_impar = 1
for i in range(n):
    print(numero_impar)
    numero_impar += 2

"""# Exercício 3

Escreva um programa que receba um número inteiro na entrada, calcule e imprima a soma dos dígitos deste número na saída

Exemplo:

Digite um número inteiro: 123

6

Dica: Para separar os dígitos, lembre-se: o operador "//" faz uma divisão inteira jogando fora o resto, ou seja, aquilo que é menor que o divisor; O operador "%" devolve apenas o resto da divisão inteira jogando fora o resultado, ou seja, tudo que é maior ou igual ao divisor.
"""

numero = int(input("Digite um número: "))

somar_digitos = 0

while numero > 0:
    digito = numero % 10
    somar_digitos += digito
    numero //= 10

print(somar_digitos)