# -*- coding: utf-8 -*-
"""ListaExercicio2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMPKO8dX1Tc9hVRKLX7_Dk6NJkZ-C72C

# Exercício 1 - Par ou ímpar?

Receba um número inteiro na entrada e imprima par quando o número for par ou ímpar quando o número for ímpar.
"""

numero = int(input("Digite um número: "))

if numero % 2 == 0:
    print("par")
else:
    print("ímpar")

"""# Exercícios 2 - FizzBuzz parcial, parte 1

Receba um número inteiro na entrada e imprima **Fizz**, se o número for divisível por 3. Caso contrário, imprima o mesmo número que foi dado na entrada.
"""

numero = int(input("Digite um número: "))
if numero % 3 == 0:
    print("Fizz")
else:
    print(numero)

"""# Exercícios 3 - FizzBuzz parcial, parte 2

Receba um número inteiro na entrada e imprima **Buzz**, se o número for divisível por 5. Caso contrário, imprima o mesmo número que foi dado na entrada.
"""

numero = int(input("Digite um número: "))
if numero % 5 == 0:
    print("Buzz")
else:
    print(numero)

"""# Exercícios 4 - FizzBuzz parcial, parte 3

Receba um número inteiro na entrada e imprima **FizzBuzz** , na saída se o número for divisível por 3 e por 5. Caso contrário, imprima o mesmo número que foi dado na entrada.
"""

numero = int(input("Digite um número inteiro: "))
if numero % 3 == 0 or numero % 5 == 0:
    print("FizzBuzz")
else:
    print(numero)

"""# Exercício 5 - Verificando ordenação

Receba 3 números inteiros na entrada e imprima **crescente**, se eles forem dados em ordem crescente. Caso contrário, imprima **não está em ordem crescente**
"""

numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))
numero3 = int(input("Digite o terceiro número: "))
if numero1 < numero2 < numero3:
    print("crescente")
else:
    print("não está em ordem crescente")